export type Locale = "en" | "zh";

export const repository = "https://github.com/NeuraSea/open-chat-cut";

export const copy = {
	en: {
		locale: "en" as const,
		altHref: "/zh/", altLabel: "中文", docsHref: "/docs/",
		nav: ["Workflow", "Local AI", "Pricing"],
		badge: "NEW", badgeText: "Fumadocs-powered docs are live",
		headline: "Edit at the speed of intent.",
		lead: "Tell the agent what the story needs. Review a precise plan, approve the diff, and keep every result editable on a real local timeline.",
		primary: "Explore the source", secondary: "Read the docs",
		note: "Local-first · source-available · Codex-ready",
		proof: [["1 revision", "per approved Agent batch"], ["≤ 1 frame", "target A/V drift"], ["Loopback", "daemon by default"], ["Your files", "managed locally"]],
		sectionKicker: "A complete creative loop", sectionTitle: "AI speed without surrendering the edit.",
		sectionBody: "OpenChatCut uses one operation engine for Agent edits and manual edits. Plans, cost, warnings, dependencies, revisions, undo and export all share the same project truth.",
		features: [
			["⌁", "Agent edits with receipts", "See the normalized timeline diff, affected assets, estimated cost and warnings before applying anything."],
			["¶", "Edit video like a document", "Remove filler words, tighten pauses, relabel speakers and preserve linked audio, video and captions."],
			["◇", "Editable motion graphics", "Build lower thirds, charts, callouts, CTAs and title cards from a safe versioned model."],
			["↧", "Generated assets stay yours", "Images, voice, B-roll, music and SFX are downloaded into the managed content-addressed library."],
			["≋", "Reversible audio work", "Denoise, normalize, compress, duck music and regenerate voice without overwriting the source."],
			["↗", "Professional delivery", "Export pinned revisions to video, audio, subtitles, alpha graphics and interchange formats."],
		],
		localKicker: "Your compute, your choice", localTitle: "Local models first. Hosted credits only when useful.",
		localBody: "Run transcription, understanding, image generation and voice on your own workstation or model server. Connect compatible providers only for capabilities you choose to send out.",
		pipeline: [["01", "Import into managed media"], ["02", "Understand locally"], ["03", "Approve semantic operations"], ["04", "Export a pinned revision"]],
		pricingKicker: "Licensing", pricingTitle: "Start personally. Pay when your work earns.",
		plans: [
			["Personal", "Free", "Personal non-commercial use and evaluation", ["One individual", "Local projects and exports", "No mandatory cloud account"], "Read BSL terms"],
			["Creator", "¥18 / $2.50", "Monthly · ¥179 / $25 annually", ["One creator · three devices", "Monetized and client videos", "100 monthly AI credits when launched"], "Request Creator License"],
			["Business", "Custom", "Team, SaaS, hosted, OEM and white-label", ["Multiple users", "Managed deployments", "Optional support and SLA"], "Request commercial terms"],
		],
		ctaTitle: "Make the cut. Keep the control.", ctaBody: "Clone the repository, start locally, and inspect every operation.",
		legal: "Source-available under Business Source License 1.1. OpenCut Classic attribution is retained separately and is not sponsorship or endorsement.",
	},
	zh: {
		locale: "zh" as const,
		altHref: "/", altLabel: "English", docsHref: "/zh/docs/",
		nav: ["工作流", "本地 AI", "价格"],
		badge: "新", badgeText: "Fumadocs 文档中心已上线",
		headline: "用表达意图的速度剪辑。",
		lead: "告诉 Agent 你想讲什么故事，审核清晰的计划和差异，再把每个结果保留在真实、本地、可继续编辑的时间线上。",
		primary: "查看源代码", secondary: "阅读文档",
		note: "本地优先 · 源码可见 · 支持 Codex",
		proof: [["1 个 revision", "每批已批准 Agent 修改"], ["≤ 1 帧", "目标音画漂移"], ["Loopback", "daemon 默认仅本机"], ["你的文件", "由本地媒体库管理"]],
		sectionKicker: "完整创作闭环", sectionTitle: "获得 AI 的速度，不交出剪辑控制权。",
		sectionBody: "Agent 和手动编辑共用同一套 Operation Engine。计划、费用、警告、依赖、版本、撤销与导出都基于同一份项目事实。",
		features: [
			["⌁", "有凭据的 Agent 剪辑", "应用前先看标准化时间线差异、受影响素材、预计费用和风险警告。"],
			["¶", "像文档一样编辑视频", "删除口头禅、压缩停顿、修改说话人，同时保持音频、视频和字幕同步。"],
			["◇", "可编辑动态图形", "使用安全版本化模型构建 lower third、图表、callout、CTA 和标题卡。"],
			["↧", "生成素材真正归你", "图片、旁白、B-roll、音乐和 SFX 都会下载进内容寻址媒体库。"],
			["≋", "可撤销音频处理", "降噪、响度、压缩、音乐闪避和局部旁白重生成都不会覆盖原文件。"],
			["↗", "专业交付", "从固定 revision 导出视频、音频、字幕、透明动态图形和交换格式。"],
		],
		localKicker: "你的算力，你的选择", localTitle: "本地模型优先，只在值得时使用托管点数。",
		localBody: "转录、内容理解、图片生成和语音都可以运行在自己的工作站或模型服务器。只有你主动选择的能力才会连接外部 Provider。",
		pipeline: [["01", "导入受管媒体库"], ["02", "使用本地模型理解"], ["03", "批准语义操作"], ["04", "导出固定 revision"]],
		pricingKicker: "许可证", pricingTitle: "个人创作免费，产生商业价值后再付费。",
		plans: [
			["Personal", "免费", "个人非商业创作和评估", ["一名个人用户", "本地项目和导出", "无需强制云端账号"], "阅读 BSL 条款"],
			["Creator", "¥18 / $2.50", "每月 · 年付 ¥179 / $25", ["一名创作者 · 三台设备", "商业化内容与客户项目", "上线后每月 100 AI 点数"], "申请 Creator 许可证"],
			["Business", "定制", "团队、SaaS、托管、OEM 与白标", ["多用户", "受管部署", "可选支持与 SLA"], "申请商业条款"],
		],
		ctaTitle: "完成剪辑，保留控制。", ctaBody: "克隆仓库，在本地启动，并检查每一项操作。",
		legal: "采用 Business Source License 1.1 源码可见许可。OpenCut Classic 归属单独保留，不代表赞助或背书。",
	},
};
