from __future__ import annotations

import json
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest
import zipfile


ROOT = Path(__file__).resolve().parents[2]
BUILD = ROOT / "scripts" / "release" / "build-manifest.py"
VERIFY = ROOT / "scripts" / "release" / "verify-release-bundle.py"
CREATE_ZIP = ROOT / "scripts" / "release" / "create-zip.py"


class ReleaseBundleTest(unittest.TestCase):
    def fixture(self, root: Path) -> None:
        files = {
            "VERSION": "0.1.0\n",
            "LICENSE": "license\n",
            "NOTICE.md": "notice\n",
            ".agents/plugins/marketplace.json": "{}\n",
            "plugins/open-chat-cut/.codex-plugin/plugin.json": "{}\n",
            "bin/openchatcutd": "binary fixture\n",
        }
        for relative, value in files.items():
            path = root / relative
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(value, encoding="utf-8")

    def test_manifest_covers_exact_bundle_and_detects_tampering(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            bundle = Path(temporary) / "openchatcut-0.1.0-test"
            bundle.mkdir()
            self.fixture(bundle)
            subprocess.run(
                [sys.executable, str(BUILD), str(bundle), "--version", "0.1.0", "--target", "test"],
                check=True,
            )
            subprocess.run([sys.executable, str(VERIFY), str(bundle)], check=True)
            manifest = json.loads((bundle / "release-manifest.json").read_text())
            self.assertEqual(manifest["version"], "0.1.0")
            (bundle / "bin/openchatcutd").write_text("tampered\n", encoding="utf-8")
            failed = subprocess.run(
                [sys.executable, str(VERIFY), str(bundle)], capture_output=True, text=True
            )
            self.assertNotEqual(failed.returncode, 0)
            self.assertIn("checksum mismatch", failed.stderr)

    def test_archive_rejects_files_outside_single_root(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            bundle = root / "openchatcut-0.1.0-test"
            bundle.mkdir()
            self.fixture(bundle)
            subprocess.run(
                [sys.executable, str(BUILD), str(bundle), "--version", "0.1.0", "--target", "test"],
                check=True,
            )
            archive = root / "openchatcut-0.1.0-test.zip"
            with zipfile.ZipFile(archive, "w") as output:
                for path in bundle.rglob("*"):
                    if path.is_file():
                        output.write(path, Path(bundle.name) / path.relative_to(bundle))
                output.writestr("._openchatcut-0.1.0-test", "unexpected metadata")
            failed = subprocess.run(
                [sys.executable, str(VERIFY), str(archive)], capture_output=True, text=True
            )
            self.assertNotEqual(failed.returncode, 0)
            self.assertIn("exactly one root directory", failed.stderr)

    def test_windows_zip_builder_produces_a_verifiable_single_root(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            bundle = root / "openchatcut-0.1.0-test"
            bundle.mkdir()
            self.fixture(bundle)
            subprocess.run(
                [sys.executable, str(BUILD), str(bundle), "--version", "0.1.0", "--target", "test"],
                check=True,
            )
            archive = root / "openchatcut-0.1.0-test.zip"
            subprocess.run([sys.executable, str(CREATE_ZIP), str(bundle), str(archive)], check=True)
            subprocess.run([sys.executable, str(VERIFY), str(archive)], check=True)

    def test_bundle_rejects_generated_python_caches(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            bundle = Path(temporary) / "openchatcut-0.1.0-test"
            bundle.mkdir()
            self.fixture(bundle)
            cache = bundle / "services/media-worker/src/package/__pycache__/worker.pyc"
            cache.parent.mkdir(parents=True)
            cache.write_bytes(b"generated bytecode")
            subprocess.run(
                [sys.executable, str(BUILD), str(bundle), "--version", "0.1.0", "--target", "test"],
                check=True,
            )
            failed = subprocess.run(
                [sys.executable, str(VERIFY), str(bundle)], capture_output=True, text=True
            )
            self.assertNotEqual(failed.returncode, 0)
            self.assertIn("generated cache artifact", failed.stderr)

    def test_bundle_rejects_version_file_manifest_mismatch(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            bundle = Path(temporary) / "openchatcut-0.1.0-test"
            bundle.mkdir()
            self.fixture(bundle)
            subprocess.run(
                [sys.executable, str(BUILD), str(bundle), "--version", "0.1.0", "--target", "test"],
                check=True,
            )
            (bundle / "VERSION").write_text("../unexpected\n", encoding="utf-8")
            failed = subprocess.run(
                [sys.executable, str(VERIFY), str(bundle)], capture_output=True, text=True
            )
            self.assertNotEqual(failed.returncode, 0)
            self.assertIn("version or target is invalid", failed.stderr)


if __name__ == "__main__":
    unittest.main()
